import { useEffect, useState, type FormEvent } from "react";
import { ImagePlus, MailPlus, Pencil, Plus, Power, Save, X } from "lucide-react";
import { DashboardShell } from "../components/DashboardShell";
import { getBusinesses, inviteOwner, saveBusiness, toggleBusiness, uploadCatalogImage } from "../lib/api";
import { slugify } from "../lib/format";
import { appHref } from "../lib/navigation";
import type { Business, BusinessType } from "../lib/types";
type Draft={id?:string;name:string;slug:string;subtitle:string;description:string;primary_color:string;accent_color:string;logo_url:string;type:BusinessType;whatsapp:string;business_hours:string;is_active:boolean};
const blank:Draft={name:"",slug:"",subtitle:"",description:"",primary_color:"#294a41",accent_color:"#f4c96b",logo_url:"",type:"both",whatsapp:"",business_hours:"",is_active:true};
export function AdminDashboard(){
 const [businesses,setBusinesses]=useState<Business[]>([]); const [draft,setDraft]=useState<Draft|null>(null); const [invite,setInvite]=useState<{business:Business;email:string}|null>(null); const [busy,setBusy]=useState(false); const [uploadingLogo,setUploadingLogo]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 async function refresh(){try{setBusy(true);setBusinesses(await getBusinesses());}catch(err:any){setError(err?.message||"Não foi possível carregar empresas.");}finally{setBusy(false);}}
 useEffect(()=>{refresh();},[]);
 function edit(b:Business){setDraft({id:b.id,name:b.name,slug:b.slug,subtitle:b.subtitle||"",description:b.description||"",primary_color:b.primary_color,accent_color:b.accent_color,logo_url:b.logo_url||"",type:b.type,whatsapp:b.whatsapp||"",business_hours:b.business_hours||"",is_active:b.is_active});}
 async function submit(e:FormEvent){e.preventDefault();if(!draft)return;try{setBusy(true);await saveBusiness({id:draft.id,name:draft.name,slug:draft.slug||slugify(draft.name),subtitle:draft.subtitle||null,description:draft.description||null,primary_color:draft.primary_color,accent_color:draft.accent_color,logo_url:draft.logo_url||null,type:draft.type,whatsapp:draft.whatsapp||null,business_hours:draft.business_hours||null,is_active:draft.is_active});setDraft(null);setNotice("Empresa salva.");await refresh();}catch(err:any){setError(err?.message||"Erro ao salvar empresa.");}finally{setBusy(false);}}
 async function toggle(b:Business){try{await toggleBusiness(b.id,!b.is_active);setBusinesses(list=>list.map(item=>item.id===b.id?{...item,is_active:!item.is_active}:item));}catch(err:any){setError(err?.message||"Erro ao alterar status.");}}
 async function sendInvite(e:FormEvent){e.preventDefault();if(!invite)return;try{setBusy(true);await inviteOwner(invite.business.id,invite.email);setNotice("Convite enviado para "+invite.email+".");setInvite(null);}catch(err:any){setError(err?.message||"Não foi possível enviar o convite.");}finally{setBusy(false);}}
 async function handleLogo(file?:File){if(!file||!draft?.id)return;try{setUploadingLogo(true);const url=await uploadCatalogImage(file,draft.id);setDraft({...draft,logo_url:url});}catch(err:any){setError(err?.message||"Não foi possível enviar a logo.");}finally{setUploadingLogo(false);}}
 const active=businesses.filter(b=>b.is_active).length;
 return <DashboardShell admin title="Empresas" eyebrow="Super admin" action={<button className="btn dark" onClick={()=>setDraft(blank)}><Plus size={16}/> Criar empresa</button>}>
 {error&&<div className="alert error">{error}<button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="alert success">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 <div className="stats"><div><span>Empresas</span><strong>{businesses.length}</strong></div><div><span>Ativas</span><strong>{active}</strong></div><div><span>Pausadas</span><strong>{businesses.length-active}</strong></div></div>
 <section className="panel"><div className="panel-head"><div><h2>Empresas cadastradas</h2><p className="muted">Cada empresa tem catálogo, identidade visual e acesso isolado.</p></div></div>{busy&&!businesses.length?<p>Carregando...</p>:<div className="business-cards">{businesses.map(b=><article className="business-card" key={b.id}><div className="business-color" style={{background:"linear-gradient(135deg,"+b.primary_color+","+b.accent_color+")"}}>{b.logo_url?<img src={b.logo_url} alt=""/>:<span>{b.name.charAt(0)}</span>}</div><div className="business-card-main"><div className="business-card-title"><div><h3>{b.name}</h3><a href={appHref("/"+b.slug)} target="_blank">/{b.slug}</a></div><span className={b.is_active?"badge":"badge off"}>{b.is_active?"Ativa":"Pausada"}</span></div><p className="muted">{b.type==="products"?"Produtos":b.type==="services"?"Serviços":"Produtos e serviços"}</p><div className="business-actions"><button className="btn tiny ghost" onClick={()=>edit(b)}><Pencil size={14}/> Editar</button><button className="btn tiny ghost" onClick={()=>setInvite({business:b,email:""})}><MailPlus size={14}/> Convidar dono</button><button className={"btn tiny "+(b.is_active?"danger-soft":"success-soft")} onClick={()=>toggle(b)}><Power size={14}/>{b.is_active?"Desligar":"Ativar"}</button></div></div></article>)}</div>}</section>
 {draft&&<div className="modal-backdrop" onClick={()=>setDraft(null)}><form className="modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">{draft.id?"Editar empresa":"Nova empresa"}</span><h2>{draft.name||"Cadastro da empresa"}</h2></div><button type="button" className="icon-btn" onClick={()=>setDraft(null)}><X size={18}/></button></div><div className="form-grid"><label>Nome<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value,slug:draft.id?draft.slug:slugify(e.target.value)})}/></label><label>Link / slug<input required value={draft.slug} onChange={e=>setDraft({...draft,slug:slugify(e.target.value)})}/></label><label>Tipo<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as BusinessType})}><option value="products">Produtos</option><option value="services">Serviços</option><option value="both">Produtos e serviços</option></select></label><label>WhatsApp<input value={draft.whatsapp} onChange={e=>setDraft({...draft,whatsapp:e.target.value})}/></label><label className="span-2">Subtítulo<input value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})}/></label><label className="span-2">Descrição<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Cor principal<div className="color-field"><input type="color" value={draft.primary_color} onChange={e=>setDraft({...draft,primary_color:e.target.value})}/><input value={draft.primary_color} onChange={e=>setDraft({...draft,primary_color:e.target.value})}/></div></label><label>Cor destaque<div className="color-field"><input type="color" value={draft.accent_color} onChange={e=>setDraft({...draft,accent_color:e.target.value})}/><input value={draft.accent_color} onChange={e=>setDraft({...draft,accent_color:e.target.value})}/></div></label><label className="span-2">Logo<input value={draft.logo_url} onChange={e=>setDraft({...draft,logo_url:e.target.value})} placeholder="URL da logo"/>{draft.id&&<span className="btn ghost file-btn"><ImagePlus size={16}/>{uploadingLogo?"Enviando...":"Enviar imagem"}<input type="file" accept="image/*" disabled={uploadingLogo} onChange={e=>handleLogo(e.target.files?.[0])}/></span>}</label><label>Horário/status<input value={draft.business_hours} onChange={e=>setDraft({...draft,business_hours:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Empresa ativa</label></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setDraft(null)}>Cancelar</button><button disabled={busy} className="btn dark"><Save size={16}/> Salvar</button></div></form></div>}
 {invite&&<div className="modal-backdrop" onClick={()=>setInvite(null)}><form className="modal small-modal" onSubmit={sendInvite} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">Convidar dono</span><h2>{invite.business.name}</h2></div><button type="button" className="icon-btn" onClick={()=>setInvite(null)}><X size={18}/></button></div><p className="muted">O usuário será criado ou convidado e vinculado somente a esta empresa.</p><label>Email do responsável<input type="email" required value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})} placeholder="dono@empresa.com"/></label><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setInvite(null)}>Cancelar</button><button disabled={busy} className="btn dark"><MailPlus size={16}/> Enviar convite</button></div></form></div>}
 </DashboardShell>;
}
