import { useEffect, useMemo, useState } from "react";
import { MessageCircle, Minus, Plus, ShoppingBag, X } from "lucide-react";
import { getPublicCatalog } from "../lib/api";
import { digits, money } from "../lib/format";
import { appHref } from "../lib/navigation";
import type { Business, CartLine, CatalogItem, Category, ItemVariant } from "../lib/types";
export function CatalogPage({slug}:{slug:string}){
 const [business,setBusiness]=useState<Business|null>(null); const [categories,setCategories]=useState<Category[]>([]); const [items,setItems]=useState<CatalogItem[]>([]); const [loading,setLoading]=useState(true); const [category,setCategory]=useState("all"); const [selectedVariants,setSelectedVariants]=useState<Record<string,string>>({}); const [cartOpen,setCartOpen]=useState(false);
 const storageKey="vitrine-cart:"+slug;
 const [cart,setCart]=useState<CartLine[]>(()=>{ try{return JSON.parse(localStorage.getItem(storageKey)||"[]");}catch{return [];} });
 useEffect(()=>{ let live=true; setLoading(true); getPublicCatalog(slug).then(result=>{if(!live)return;if(result){setBusiness(result.business);setCategories(result.categories);setItems(result.items);document.title=result.business.name+" — Catálogo";}else setBusiness(null);}).catch(()=>setBusiness(null)).finally(()=>live&&setLoading(false)); return()=>{live=false;}; },[slug]);
 useEffect(()=>{ try{localStorage.setItem(storageKey,JSON.stringify(cart));}catch{} },[cart,storageKey]);
 const visible=useMemo(()=>category==="all"?items:items.filter(i=>i.category_id===category),[items,category]);
 const total=cart.reduce((sum,line)=>sum+((line.variant?.price??line.item.price)??0)*line.qty,0); const duration=cart.reduce((sum,line)=>sum+(line.item.duration_minutes??0)*line.qty,0); const count=cart.reduce((sum,line)=>sum+line.qty,0);
 function add(item:CatalogItem){ const selectedId=selectedVariants[item.id]||item.variants?.[0]?.id; const variant=item.variants?.find(v=>v.id===selectedId); setCart(current=>{const index=current.findIndex(line=>line.item.id===item.id&&line.variant?.id===variant?.id);if(index>=0)return current.map((line,i)=>i===index?{...line,qty:line.qty+1}:line);return [...current,{item,variant,qty:1}];}); }
 function changeQty(index:number,delta:number){ setCart(current=>current.flatMap((line,i)=>{if(i!==index)return[line];const qty=line.qty+delta;return qty<=0?[]:[{...line,qty}];})); }
 function send(){ if(!business||!cart.length)return; const lines=cart.map(line=>"• "+line.qty+"x "+line.item.name+(line.variant?" ("+line.variant.name+")":"")+" — "+money(line.variant?.price??line.item.price)); const message=["Olá, "+business.name+"! Quero fazer este pedido:","",...lines,"",duration?"Duração total estimada: "+duration+" min":"","Total: "+money(total)].filter(Boolean).join("\n"); window.open("https://wa.me/"+digits(business.whatsapp||"")+"?text="+encodeURIComponent(message),"_blank","noopener,noreferrer"); }
 if(loading)return <main className="catalog center-screen dark-center"><div className="loader light-loader"/><p>Carregando catálogo...</p></main>;
 if(!business)return <main className="offline"><div className="offline-card"><span className="eyebrow light">Vitrine Local</span><h1>Catálogo temporariamente indisponível</h1><p>Este catálogo não existe, está pausado ou ainda não foi publicado.</p><a className="btn glass-btn" href={appHref("/")}>Voltar ao início</a></div></main>;
 const cartPanel=<><div className="cart-title"><h2>Seu pedido</h2><button className="icon-btn mobile-only" onClick={()=>setCartOpen(false)} aria-label="Fechar carrinho"><X size={18}/></button></div>{cart.length===0?<p className="muted-light">Adicione itens para montar o pedido.</p>:cart.map((line,index)=><div className="cart-line" key={line.item.id+"-"+(line.variant?.id||"base")}><div><strong>{line.item.name}</strong><span>{line.variant?.name||money(line.item.price)}</span></div><div className="qty"><button onClick={()=>changeQty(index,-1)}><Minus size={12}/></button>{line.qty}<button onClick={()=>changeQty(index,1)}><Plus size={12}/></button></div></div>)}<div className="total"><span>Total</span><strong>{money(total)}</strong></div>{duration>0&&<small className="muted-light">Duração estimada: {duration} min</small>}<button disabled={!cart.length||!business.whatsapp} onClick={send} className="btn whatsapp full"><MessageCircle size={16}/> Enviar pelo WhatsApp</button></>;
 return <main className="catalog" style={{"--biz-primary":business.primary_color,"--biz-accent":business.accent_color} as React.CSSProperties}><div className="catalog-shell"><header className="catalog-nav"><div className="biz">{business.logo_url?<img className="logo-img" src={business.logo_url} alt={"Logo "+business.name}/>:<div className="logo">{business.name.charAt(0)}</div>}<div><strong>{business.name}</strong><span>{business.subtitle||business.type}</span></div></div><button className="cart-chip" onClick={()=>setCartOpen(true)}><ShoppingBag size={17}/>{count}</button></header><div className="catalog-grid"><section><div className="catalog-hero"><span className="status"><i/> {business.business_hours||"Consulte o horário"}</span><h1>{business.subtitle||"Escolha, adicione e peça."}</h1><p>{business.description||"Monte seu pedido e envie tudo pronto pelo WhatsApp."}</p><div className="actions"><a className="btn accent" href="#catalogo">Ver catálogo</a>{business.whatsapp&&<a className="btn glass-btn" target="_blank" rel="noreferrer" href={"https://wa.me/"+digits(business.whatsapp)}><MessageCircle size={16}/> Falar no WhatsApp</a>}</div></div><div id="catalogo" className="tabs"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>Todos</button>{categories.map(cat=><button key={cat.id} className={category===cat.id?"active":""} onClick={()=>setCategory(cat.id)}>{cat.name}</button>)}</div><div className="products">{visible.map(item=><article className="product" key={item.id}>{item.image_url?<img src={item.image_url} alt={item.name}/>:<div className="image-placeholder">Sem foto</div>}<div className="product-body"><h3>{item.name}</h3><p>{item.description}</p>{Boolean(item.variants?.length)&&<select value={selectedVariants[item.id]||item.variants![0].id} onChange={e=>setSelectedVariants(value=>({...value,[item.id]:e.target.value}))}>{item.variants!.map((variant:ItemVariant)=><option key={variant.id} value={variant.id}>{variant.name}{variant.price!=null?" · "+money(variant.price):""}</option>)}</select>}<div className="product-foot"><div><strong>{money(item.price)}</strong>{item.duration_minutes&&<span>{item.duration_minutes} min</span>}</div><button onClick={()=>add(item)} aria-label={"Adicionar "+item.name}><Plus size={18}/></button></div></div></article>)}</div>{!visible.length&&<div className="empty-state">Nenhum item nesta categoria.</div>}</section><aside className="cart">{cartPanel}</aside></div></div>{count>0&&<div className="mobile-cart"><div><small>{count} item(ns)</small><strong>{money(total)}</strong></div><button className="btn whatsapp" onClick={()=>setCartOpen(true)}>Ver pedido</button></div>}{cartOpen&&<div className="cart-drawer-backdrop mobile-only" onClick={()=>setCartOpen(false)}><aside className="cart cart-drawer" onClick={e=>e.stopPropagation()}>{cartPanel}</aside></div>}</main>;
}
